const GET_DOGS = "GET_DOGS";
const GET_DOGS_BY_ID = "GET_DOGS_BY_ID";
const CLEAN_DETAIL = "CLEAN_DETAIL";
const GET_TEMPERAMENTS = "GET_TEMPERAMENTS"
const ORDER_BY_NAME = "ORDER_BY_NAME"
const ORDER_BY_TEMPERAMENT = "ORDER_BY_TEMPERAMENT"
const RESET_FILTER = "RESET_FILTER"

module.exports = {RESET_FILTER,ORDER_BY_TEMPERAMENT, GET_DOGS, GET_DOGS_BY_ID,CLEAN_DETAIL,GET_TEMPERAMENTS,ORDER_BY_NAME };
