const GET_DOGS = "GET_DOGS";
const GET_DOGS_BY_ID = "GET_DOGS_BY_ID";
const CLEAN_DETAIL = "CLEAN_DETAIL";
const GET_TEMPERAMENTS = "GET_TEMPERAMENTS"
const POST_DOG = "POST_DOG"

module.exports = { GET_DOGS, GET_DOGS_BY_ID,CLEAN_DETAIL,GET_TEMPERAMENTS,POST_DOG };
